webtalk_init -webtalk_dir C:/Users/Monica Pedro/Documents/ECE_524/Final_Project/Serial-to-Parallel-Converter/Serial-to-Parallel-Converter.sim/sim_1/behav/xsim/xsim.dir/Shift_reg_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu May 16 10:20:22 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "854e550b-d8a5-4b2a-9917-16b104403a9a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1087fa2ea9d2463cbf11e8ca930e2394" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "34" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8156_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3340259038 -regid "" -xml C:/Users/Monica Pedro/Documents/ECE_524/Final_Project/Serial-to-Parallel-Converter/Serial-to-Parallel-Converter.sim/sim_1/behav/xsim/xsim.dir/Shift_reg_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Monica Pedro/Documents/ECE_524/Final_Project/Serial-to-Parallel-Converter/Serial-to-Parallel-Converter.sim/sim_1/behav/xsim/xsim.dir/Shift_reg_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Monica Pedro/Documents/ECE_524/Final_Project/Serial-to-Parallel-Converter/Serial-to-Parallel-Converter.sim/sim_1/behav/xsim/xsim.dir/Shift_reg_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
